### ISSUE TITLE
Track improvements to make to the scan data structure

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#118]
* [x] Figure out how to reorder the JSON so that Target URL (and preferably the other target_url_xxx fields) are at the front.  
* [ ] Add a field for origin source of the URL - #196 
* [ ] ~Add a field for the target URL server code? (what is used for target_url_redirects).~  
* [ ] Rename home_scan to final_url_scan - #197
* [ ] Decide if we want the order of the fields to line up with the data dictionary - #198
* [ ] Remove the 4 scan_status_detail fields from the API (and CSV)- #199
