### ISSUE TITLE
create a checklist for adding new fields to our data

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#640]
Maybe include it as a simple template that can be copied into new issues.  

Draft: 
* [ ] Confirm field ID
* [ ] Confirm data type and nature 
* [ ] Confirm location in the CSV 
* [ ] Give search.gov team a heads up if order of `final_url_live` and `target_url_redirects` would change.  
* [ ] Update the [data dictionary](https://github.com/GSA/site-scanning-documentation/blob/main/data/Site_Scanning_Data_Dictionary.csv)
* [ ] Add the fields to [this issue](https://github.com/GSA/site-scanning/issues/376) 
* [ ] Update [this table](https://digital.gov/guides/site-scanning/understand-the-data/)
* [ ] Greenlight @akuny updating the API and snapshots

**Comment by gbinal** [comment]
done
