### ISSUE TITLE
Checklist for new fields - a11y 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#652]
* [ ] Confirm field ID
* [ ] Confirm data type and nature
* [ ] Confirm location in the CSV
* [ ] Give search.gov team a heads up if order of final_url_live and target_url_redirects would change.
* [ ] Update the [data dictionary](https://github.com/GSA/site-scanning-documentation/blob/main/data/Site_Scanning_Data_Dictionary.csv)
* [ ] Add the fields to https://github.com/GSA/site-scanning/issues/376
* [ ] Update [this table](https://digital.gov/guides/site-scanning/understand-the-data/)
* [ ] Greenlight @akuny updating the API and snapshots

**Comment by gbinal** [comment]
The field names and their locations should be: 
* accessibility_scan_status - after dns_scan_status
* a11y_missing_img_alt_issues - at the end in its current order
* a11y_html_attribute_issues - at the end in its current order
* a11y_color_contrast_issues - at the end in its current order

**Comment by gbinal** [comment]
Alright - I'm comparing the old and new data [here](https://docs.google.com/spreadsheets/d/1TnhgpnpSkyYXZrwmD7jdVKqKXG7wS9HkCtj8gVB18UY/edit#gid=818633306).  

Of our 15,104 websites in a current primary snapshot, 11,710 match with an entry from the 12,970 websites in the itdashboard export.  

* 10,480 of the 11,710 agree on the image alt text scan.  1,230 disagree.  
* 9,031 of the 11,710 agree on the html attribute scan.  2,679 disagree.  
* 9,670 of the 11,710 agree on the color contrast scan.  2,040 disagree.  

A bigger issue is that 3,416 of the 11,710 have no scan results from the Site Scanning data because the scan failed.  Note that in each of those cases though, the primary scan completed.  

As a next step, we should investigate and try to remedy that high scan failure rate and then compare the data afresh.  


Why do they have sites that we don't?

**Comment by gbinal** [comment]
Take 3: 

[New scan data](https://docs.google.com/spreadsheets/d/10LxyQ8xl7pdqpooGOKnrXQih1N_vN48ATTc34cOZdoE/edit#gid=1966682451) | [Snapshot of ITDB ](https://docs.google.com/spreadsheets/d/13SD6FwhoJ29vJvG9AnLSr9FJIrZv_6055O5GvekvIUI/edit#gid=1539128153)| [Analysis](https://docs.google.com/spreadsheets/d/13SD6FwhoJ29vJvG9AnLSr9FJIrZv_6055O5GvekvIUI/edit#gid=767719924)
