### ISSUE TITLE
Checklist for new fields - 2x TLD fields 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#655]
* [x] Confirm field ID
* [x] Confirm data type and nature
* [x] Confirm location in the CSV
* [x] Give search.gov team a heads up if order of final_url_live and target_url_redirects would change.'
* [x] Review data to make sure it aligns with existing public data 
* [x] Update the [data dictionary](https://github.com/GSA/site-scanning-documentation/blob/main/data/Site_Scanning_Data_Dictionary.csv)
* [x] Add the fields to https://github.com/GSA/site-scanning/issues/376
* [x] Update [this table](https://digital.gov/guides/site-scanning/understand-the-data/)
* [x] Greenlight @akuny updating the API and snapshots 
* [x] Update itdb team & co.

**Comment by gbinal** [comment]
done
