### ISSUE TITLE
Checklist for new field - viewport tag

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#658]
* [x] Confirm field ID
* [x] Confirm data type and nature
* [x] Confirm location in the CSV
* [x] Give search.gov team a heads up if order of final_url_live and target_url_redirects would change.'
* [x] Review data to make sure it aligns with existing public data - in process [here](https://docs.google.com/spreadsheets/d/1TnhgpnpSkyYXZrwmD7jdVKqKXG7wS9HkCtj8gVB18UY/edit#gid=1413554738)
* [x] Update the [data dictionary](https://github.com/GSA/site-scanning-documentation/blob/main/data/Site_Scanning_Data_Dictionary.csv)
* [x] Add the fields to https://github.com/GSA/site-scanning/issues/376
* [x] Update [this table](https://digital.gov/guides/site-scanning/understand-the-data/)
* [x] Greenlight @akuny updating the API and snapshots 
* [x] Update itdb team & co.

**Comment by gbinal** [comment]
When reviewing our data against existing data, here's some issues we're seeing:  

No viewport tag, but registered as mobile-friendly on itdb:
* iowanation.nsopw.gov
*

**Comment by gbinal** [comment]
done
