### ISSUE TITLE
create a checklist for notifying consumers about breaking changes 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#681]
The two places we could break things for people are the snapshot and API.  Likely, any change would take place in both, but the way to communicate with current users might be different.  

* [ ] Look up email addresses from API users for the past 3 months
* [ ] Note known snapshot consumers (currently, just search.gov)
* [ ] Message them with the time and nature of the upcoming changes 
* [ ] Add a banner to the API documentation

**Comment by gbinal** [comment]
posted this [here](https://github.com/GSA/site-scanning-documentation/blob/main/about/project-management/team-workflows.md#checklist-for-notifying-users-about-upcoming-breaking-changes), closing issue
